# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

jobs:
  - job: Linux
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - task: NodeTool@0
        displayName: "Use Node 10.x"

      - task: Npm@1
        displayName: "npm install"
        inputs:
          verbose: false

      - script: npm build
        displayName: "Build the package"

      - script: npm run pkg -- --out-path $(Build.ArtifactStagingDirectory)
        displayName: "Pack the package artifacts"

      - task: PublishBuildArtifacts@1
        displayName: "Publish linux artifacts"
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "Observer"
          publishLocation: "Container"
